services:
  command_bus:
    class: EricksonReyes\DomainDrivenDesign\Application\CommandBus
    calls:
      - [addHandler, ['@create_order_handler', Fulfillment\Application\CreateOrder ]]
      - [addHandler, ['@accept_order_handler', Fulfillment\Application\AcceptOrder]]
      - [addHandler, ['@cancel_order_handler', Fulfillment\Application\CancelOrder ]]
      - [addHandler, ['@close_order_handler', Fulfillment\Application\CloseOrder]]
      - [addHandler, ['@ship_order_handler', Fulfillment\Application\ShipOrder]]