services:
  event_store:
    class: App\Services\EventStorages\EventStore
    arguments: ['@mysql_event_storage']
    calls:
      - [addPublisher, ['@rabbitmq_event_publisher']]
      - [addRepository, ['@elasticsearch_event_storage']]