#!/bin/bash
php -i | grep "\.ini" | grep -o -e '\(/[a-z0-9._-]\+\)\+\.ini' | grep -v xdebug | xargs awk 'FNR==1{print ""}1' | grep -v xdebug > php.ini.bak
grep -vwE "(opcache|OPcache|xdebug|apcu|bcmath|bz2|calendar|exif|gd|imagick|imap|intl|ldap|memcached|mongodb|mysqli|pcntl|pdo_mysql|pdo_pgsql|pgsql|redis|soap|sodium|xmlrpc|zip)" php.ini.bak > php.ini
rm php.ini.bak